In [1]:
#Dictionary
student = {
    "name": "John Doe",
    "age": 20,
    "major": "Computer Science",
    "courses": ["Data Structures", "Algorithms", "Operating Systems"],
}
print(student)

{'name': 'John Doe', 'age': 20, 'major': 'Computer Science', 'courses': ['Data Structures', 'Algorithms', 'Operating Systems']}


In [2]:
student["major"]

'Computer Science'

In [3]:
student["courses"]

['Data Structures', 'Algorithms', 'Operating Systems']

In [5]:
student["age"]

20

In [7]:
student.get("age")

20

In [8]:
student["age"] = 21

In [9]:
student

{'name': 'John Doe',
 'age': 21,
 'major': 'Computer Science',
 'courses': ['Data Structures', 'Algorithms', 'Operating Systems']}

In [10]:
del student["major"] # Remove the major key

In [11]:
student

{'name': 'John Doe',
 'age': 21,
 'courses': ['Data Structures', 'Algorithms', 'Operating Systems']}

In [12]:
student["cgpa"]=3.50

In [13]:
student

{'name': 'John Doe',
 'age': 21,
 'courses': ['Data Structures', 'Algorithms', 'Operating Systems'],
 'cgpa': 3.5}

In [15]:
student.keys()

dict_keys(['name', 'age', 'courses', 'cgpa'])

In [16]:
student.values()

dict_values(['John Doe', 21, ['Data Structures', 'Algorithms', 'Operating Systems'], 3.5])

In [18]:
student_db = {
    "s001": {"name": "Alice", "age": 22, "major": "Mathematics"},
    "s002": {"name": "Bob", "age": 21, "major": "Physics"},
}
student_db

{'s001': {'name': 'Alice', 'age': 22, 'major': 'Mathematics'},
 's002': {'name': 'Bob', 'age': 21, 'major': 'Physics'}}

In [19]:
student_db["s001"]

{'name': 'Alice', 'age': 22, 'major': 'Mathematics'}

##Numpy

In [21]:
!pip install numpy

In [22]:
import numpy
arr=numpy.array([2,4,6])
print(arr)

[2 4 6]


In [23]:
type(arr)

numpy.ndarray

In [25]:
arr = numpy.array([2,4,6])

In [26]:
import numpy as np 
arr = np.array((2,4,6))
print(arr)


[2 4 6]


In [27]:
type(arr)

numpy.ndarray

In [28]:
arr.ndim

1

In [30]:
arr2=np.array([[2,4,5]])
arr2.ndim
print(arr2)

[[2 4 5]]


In [32]:
arr2=np.array([[[2,4,5]]])
arr2.ndim

3

In [36]:
arr=np.array([[2,4,5],[5,7,8]])
print(arr)

[[2 4 5]
 [5 7 8]]


In [37]:
arr.ndim

2

In [ ]:
arr.shape#(row,column)

(2, 3)

In [39]:
arr=np.array([[2,4,5],[3,5,9]])
print(arr)

[[2 4 5]
 [3 5 9]]


In [40]:
len([2,3,5])

3

In [ ]:
arr=np.array([[[2,5,1],[5,8,9]],[[2,1,3],[6,6,8]]])
print(arr)
arr.shape #shape:(num1,num2.num3) each num is a block 

[[[2 5 1]
  [5 8 9]]

 [[2 1 3]
  [6 6 8]]]


(2, 2, 3)

In [45]:
arr=np.array([2,3,4])
arr.shape

(3,)

In [46]:
a=np.array([1,"name",1.25])
print(a)

['1' 'name' '1.25']


In [47]:
a.dtype

dtype('<U32')

In [48]:
zero_arr = np.zeros((2,3))
print(zero_arr)

[[0. 0. 0.]
 [0. 0. 0.]]


In [49]:
round_arr = np.zeros((3,3))
print(round_arr)

[[0. 0. 0.]
 [0. 0. 0.]
 [0. 0. 0.]]


In [ ]:
ones_arr = np.ones((2,3))# Create a 2D array of ones with shape (2, 3)
print(ones_arr)

[[1. 1. 1.]
 [1. 1. 1.]]


In [51]:
range_arr = np.arange(1, 10, 2)  # Create an array with values from 1 to 9 with a step of 2
print(range_arr)

[1 3 5 7 9]


In [52]:
linespace_arr = np.linspace(1, 10, 5)  # Create an array with 5 evenly spaced values between 1 and 10
print(linespace_arr)

[ 1.    3.25  5.5   7.75 10.  ]


### Indexing and Slicing

In [ ]:
arr=np.array([2,3,5,7])
print(arr)
arr[1:3]


[2 3 5 7]


array([3, 5])

In [56]:
arr=np.array([[2,3,5],[2,1,6],[5,7,10]])
print(arr)

[[ 2  3  5]
 [ 2  1  6]
 [ 5  7 10]]


In [59]:
arr.shape

(3, 3)

In [ ]:
arr[0,0] #print 2

np.int64(2)

In [ ]:
arr[1,1] #print 1

np.int64(1)

In [63]:
arr[2,1]

np.int64(7)

In [64]:
arr[1:3,1:3] # Slicing rows 1 to 2 and columns 1 to 2

array([[ 1,  6],
       [ 7, 10]])

In [66]:
arr[0:2,0:2] # Slicing rows 0 to 1 and columns 0 to 1

array([[2, 3],
       [2, 1]])

In [68]:
arr[0:3,0:3]

array([[ 2,  3,  5],
       [ 2,  1,  6],
       [ 5,  7, 10]])

In [72]:
arr[1:3,1:3]

array([[ 1,  6],
       [ 7, 10]])

In [ ]:
arr=np.array([[[[3,5,7],8,10]]])
arr[0,1,0]

np.int64(6)

In [74]:
arr[0,0,1:3]

array([5, 7])

In [75]:
arr=np.array([[[3,5,7],[8,10,2]],[[10,20,30],[24,26,29]]])
print(arr)

[[[ 3  5  7]
  [ 8 10  2]]

 [[10 20 30]
  [24 26 29]]]


In [76]:
arr[1,1,1]

np.int64(26)

In [77]:
a=np.array([1,2,3])
b=np.array([4,5,6])
print(a+b)  # Element-wise addition
print(a-b)  # Element-wise subtraction

[5 7 9]
[-3 -3 -3]


In [78]:
matrix = np.array([[1, 2], [3, 4]])
scalar_added = matrix + 10
print(scalar_added)  # Adding a scalar to each element of the matrix

[[11 12]
 [13 14]]


In [80]:
matrix = np.array([[1, 2], [3, 4]])
print(matrix*2)

[[2 4]
 [6 8]]


In [81]:
matrix1 = np.array([[1, 2], [3, 4]])
matrix2 = np.array([[5, 6], [7, 8]])
matrix1@matrix2  # Element-wise multiplication


array([[19, 22],
       [43, 50]])

In [82]:
matrix1

array([[1, 2],
       [3, 4]])

In [83]:
data = np.array([[1, 2], [3, 4]])
np.sum(data) # Sum of all elements in the array

np.int64(10)

In [85]:
data = np.array([[1, 2], [3, 4]])
data.std # Shape of the array

<function ndarray.std>

In [16]:
import numpy as np 
a = np.array([10,20,30,40,50]) # Created 2 arrays
b = np.array([5,15,25,35,45]) 
#Performed basic calculations on the array for the first array
print("sum:",np.sum(a))
print("mean:",np.mean(a))
print("maximum:",np.max(a))
print("minimum:",np.min(a))
print("standard deviation:",np.std(a))
print("shape:",a.shape)
print("dimention:",a.ndim)#Explored array properties
print("data type:",a.dtype)
print("size:",a.size)
a2 = a.reshape(5,1) # Reshaped the array
print(a2)
a[2] # indexing and slicing
a[0:3]
print(a+b) # addition
print(a*b) # multiplication

sum: 150
mean: 30.0
maximum: 50
minimum: 10
standard deviation: 14.142135623730951
shape: (5,)
dimention: 1
data type: int64
size: 5
[[10]
 [20]
 [30]
 [40]
 [50]]
[15 35 55 75 95]
[  50  300  750 1400 2250]
